### ISSUE TITLE
unrecognized arguments: -ai 50

### ISSUE THREAD

**Issue by mieczyslaw** [karanicolaslab/PROTAC_ternary#3]
I believe the readme needs to be updated, as there is no `ai` parameter anymore leading to:

ternary_model_prediction.py: error: unrecognized arguments: -ai 50

**Comment by mieczyslaw** [comment]
this still seems to be valid agter recent update @sven-miller , I suppose README needs an update

**Comment by sven-miller** [comment]
@mieczyslaw the -ai argument is included in the most recent script, currently defaults to 5 iterations which in most cases provides sufficient convergence

**Comment by mieczyslaw** [comment]
yes, it works now, thanks
