### ISSUE TITLE
atom_list & atom_delete format explanation

### ISSUE THREAD

**Issue by mieczyslaw** [karanicolaslab/PROTAC_ternary#5]
Could you please add the explanation to the readme regarding the format of atom_list & atom_delete?

I understand that the first word is residue name and then atom name. However, some lists in Example contain several atom names in the line:
```
LG1 S1 C21 C20 C18
LG1 C17
LG1 C2
LG2 C7 C6 C13 C11 C10
LG2 C12
LG2 N3
```
whereas others always a single atom name:
```
UNL S20 
UNL C4 
UNL C7 
UNL C8
UNL C10
UNL C1
UNL C2 
UNL C3 
UNL C5 
UNL C6
UNL C9
```

What's the logic behind providing one atom name per line vs several atom names per line?

**Comment by mieczyslaw** [comment]
@sven-miller could you explain the format, after recent update it is still mysterious

**Comment by sven-miller** [comment]
@mieczyslaw lines that include multiple atoms on a single line define a "centroid" (this usually is applied to benzene rings). Atoms on single lines specify that atom alone will be used to calculate the RMSD for linker/decoy overlay. I recommend that the order of atoms between linker and decoy lists remain consistent: 
for example;
(Linker)                        (Decoy)
UNL O2                        KIN O4
UNL C4                        KIN C12
UNL C3 C4  C5 C6      KIN C8 C9 C10 C11

In the delete lists, all atoms can be put on single lines, in any order. 

The combination of atoms used for RMSD calculation and delete lists will vary  depending on how you desire to modeling the connectivity of the linker and decoys

**Comment by mieczyslaw** [comment]
Thank you @sven-miller . It would be great to add it to README.
