### ISSUE TITLE
a way to deal with hydrogen atoms when linking

### ISSUE THREAD

**Issue by mieczyslaw** [karanicolaslab/PROTAC_ternary#6]
The readme says:

- decoy_atom_list.txt & linker_atom_list.txt: atoms would be used to do the alignment
- decoy_atom_delete.txt & linker_atom_delte.txt: atoms which are repeated in decoy / conformer and need to be deleted

It means that all or subset of duplicated atoms can be used for alignment.

However, it is not obvious how to deal with hydrogen atoms - the example doesn't include them for deletion but PDBs contain hydrogen atoms. When linking, some of them may not be needed anymore. It would be good to explain this in readme.

**Comment by sven-miller** [comment]
I am a postdoc in the Karanicolas lab and I would be happy to answer your question, but we actually have updated code that we hope to make available in the next two weeks. I will keep you updated.

**Comment by mieczyslaw** [comment]
Dear @sven-miller, thanks for letting me know. I will be waiting for the updated version (I suppose you've already spotted some syntax errors like quit() typo etc.).

**Comment by heritiem** [comment]
Dear @sven-miller,

I am also very interested in the code and started using it for my project. Could you give us some information about when the updated code will be available ?

Best regards

**Comment by sven-miller** [comment]
Dear @mieczyslaw and @heritiem, we have updated the code and hope you find that the issues have been solved. Please let me know if you have any further questions.

**Comment by mieczyslaw** [comment]
Thanks for the update @sven-miller ! An extra question, if I can :)

<=0.4A you mention in the preprint, is this RMSD of the stub, or of the attachment point? calculated separately for two tails, or total?

Can you provide in the repo a few examples with inputs showing such a small RMSD I can run myself? Are you getting solutions below <0.4A when starting from unbound proteins or you only worked with bound complex so far?

As I needed the linking quickly, I coded it myself, but happy to compare with your tool! As I followed up with the same input strategy (stubs etc.), it would be interesting to see the impact of your minimizer.

Thanks again, and I will let you know when I test it (may be after Christmas as the holiday season is coming soon!).

**Comment by mieczyslaw** [comment]
@sven-miller as far as I see in the updated code, you ignore hydrogen atoms?

**Comment by sven-miller** [comment]
@mieczyslaw yes RMSD is calculated on both sides, as defined by the linker/decoy atom lists. Hydrogens can be specified if desired, simply add them to the list. The updated script can handle any number of atoms in either list (depending on your desired stringency). We are planning to make our data sets available very soon and the updated manuscript will provide additional explanation to guide defining decoy/linker atom lists.

**Comment by mieczyslaw** [comment]
@sven-miller how new align from RDKit compares with the Powell method you used in the older version? Are you still getting the same RMSD after linking?
